# Generated by Django 2.1.11 on 2019-08-08 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbinforeport',
            name='ftype',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='dbinforeport',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='dbinforeport',
            name='note',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='dbinforeport',
            name='value',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
