# Generated by Django 2.1.11 on 2019-08-08 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_auto_20190808_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sqlstatsqlonlyreport',
            name='sql_plan',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='sqlstatsqlonlyreport',
            name='sql_text',
            field=models.TextField(null=True),
        ),
    ]
