# Generated by Django 2.1.11 on 2019-08-07 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbconn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbconn',
            name='sid',
            field=models.CharField(default='TEST', max_length=50),
        ),
        migrations.AlterField(
            model_name='history',
            name='instance_number',
            field=models.IntegerField(default=1),
        ),
    ]
